name: Bug report
description: Create a report to help us improve 2501 DeepMemory
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run 2501.py
        2. Unlock Ghost
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please paste any console logs or error tracebacks here.
      render: shell
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of 2501 DeepMemory are you using?
      placeholder: v1.1.0
